export const colorPalette = {
  p1: {
    bg: "bg-slate-950",
    navBg: "bg-slate-600",
    primary: "text-white",
    secondary: "text-gray-400",
    accent: "group-hover:bg-slate-200 group-focus-visible:bg-slate-200",
    cardHover: "hover:bg-gray-800",
    groupHover: "group-hover:text-teal-500",
    btn: "bg-teal-400/10 text-teal-300",
    bdr: "border-teal-400",
  },
  p2: {
    bg: "bg-gradient-to-r from-slate-900 to-black",
    primary: "text-white",
    secondary: "text-gray-400",
    accent:
      "group-hover:bg-slate-[#18e0c7] group-focus-visible:bg-slate-[#18e0c7]",
    navBg: "bg-[#243b4a]",
    cardHover: "hover:bg-gray-800",
    groupHover: "group-hover:text-amber-500",
    btn: "bg-amber-400/10 text-amber-300",
    bdr: "border-teal-400",
  },
  p3: {
    bg: "bg-[#0A1E26]",
    navBg: "bg-slate-600",
    primary: "text-white",
    secondary: "text-gray-400",
    accent: "group-hover:bg-slate-200 group-focus-visible:bg-slate-200",
    cardHover: "hover:bg-gray-800",
    groupHover: "group-hover:text-cyan-500",
    btn: "bg-cyan-400/10 text-cyan-300",
    bdr: "border-teal-400",
  },

  p4: {
    bg: "bg-[linear-gradient(135deg,_#fdfbfb,_#ebedee)]",
    navBg: "bg-gray-600",
    primary: "text-black",
    secondary: "text-gray-600",
    accent: "group-hover:bg-black group-focus-visible:bg-black",
    cardHover: "hover:bg-gray-200",
    groupHover: "group-hover:text-slate-800",
    btn: "bg-slate-800/10 text-slate-600",
    bdr: "border-teal-400",
  },
  p5: {
    bg: "bg-gradient-to-bl from-blue-950 via-cyan-900 to-blue-900",
    navBg: "bg-blue-900/20 backdrop-blur-lg",
    primary: "text-blue-50",
    secondary: "text-blue-300",
    accent: "group-hover:bg-blue-800/30 group-focus-visible:bg-blue-800/30",
    cardHover: "hover:bg-blue-950/40",
    groupHover: "group-hover:text-cyan-400",
    btn: "bg-cyan-500/20 text-cyan-300 hover:bg-cyan-500/30",
    bdr: "border-teal-400",
  },
}
